export const countrySongs = [
    {
      id: 1,
      link: "/music/playlist/4096400722/type/dz",
      image: "/images/k-pop.jpg",
      title: "K-Pop",
      text: "Dive into the vibrant world of Korean Pop with our playlist.",
    },
    {
      id: 2,
      link: "/music/playlist/1440614715/type/dz",
      image: "/images/afro.jpg",
      title: "Afro",
      text: "Experience the best of Afrobeat and Nigerian music.",
    },
    {
      id: 3,
      link: "/music/playlist/1420459465/type/dz",
      image: "/images/french.jpg",
      title: "French",
      text: "Explore the best of French music with our curated playlist.",
    },
    {
      id: 4,
      link: "/music/playlist/6049895724/type/dz",
      image: "/images/j-pop.jpg",
      title: "J-Pop",
      text: "Discover the latest hits from Japan's pop music scene.",
    },
    {
      id: 5,
      link: "/music/playlist/1183242961/type/dz",
      image: "/images/funk.jpg",
      title: "Brazilian Funk",
      text: "Get ready to dance with the hottest Brazilian funk tracks.",
    },
    {
      id: 6,
      link: "/music/playlist/178699142/type/dz",
      image: "/images/latin.jpg",
      title: "Latin",
      text: "Feel the heat with our selection of Latin hits.",
    }
  ];
  
  export const genre = [
    {
      id: 1,
      link: "/music/playlist/2228601362/type/dz",
      image: "/images/pop.jpg",
      title: "Fresh Pop",
      text: "Discover the best releases with our fresh pop selection.",
    },
    {
      id: 2,
      link: "/music/playlist/706093725/type/dz",
      image: "/images/edm.jpg",
      title: "Dance & EDM",
      text: "Feel the beat with our dance and EDM playlist.",
    },
    {
      id: 3,
      link: "/music/playlist/02okEcUQXHe2sS5ajE9XG0/type/sp",
      image: "/images/hip-hop.jpg",
      title: "Hip-Hop",
      text: "Explore the latest and greatest in hip-hop.",
    },
    {
      id: 4,
      link: "/music/playlist/1999466402/type/dz",
      image: "/images/rnb.jpg",
      title: "R&B",
      text: "Experience the smoothest R&B tracks.",
    },
    {
      id: 5,
      link: "/music/playlist/13754510761/type/dz",
      image: "/images/rap.jpg",
      title: "Rap",
      text: "Dive into the world of rap with our curated playlist.",
    },
    {
      id: 6,
      link: "/music/playlist/10434450042/type/dz",
      image: "/images/female_rap.jpg",
      title: "Female Rap",
      text: "Watch women take over the rap industry with these hits",
    },
    {
      id: 7,
      link: "/music/playlist/1370794195/type/dz",
      image: "/images/rock.jpg",
      title: "Rock",
      text: "Explore the best rock tracks from the past and present.",
    },
    {
      id: 8,
      link: "/music/playlist/10973071682/type/dz",
      image: "/images/folk.jpg",
      title: "Folk & Acoustic",
      text: "Enjoy the soothing sounds of folk and acoustic music.",
    },
    {
      id: 9,
      link: "/music/playlist/1477723445/type/dz",
      image: "/images/indie.jpg",
      title: "Indie love",
      text: "Discover the best indie tracks for your next love story.",
    },
    {
      id: 10,
      link: "/music/playlist/1950386602/type/dz",
      image: "/images/soul.jpg",
      title: "Soul",
      text: "Experience the depth of soul music with our curated playlist.",
    },
    {
      id: 11,
      link: "/music/playlist/1615514485/type/dz",
      image: "/images/jazz.jpg",
      title: "Jazz",
      text: "Relax with the smooth sounds of jazz.",
    },
    {
      id: 12,
      link: "/music/playlist/1132251583/type/dz",
      image: "/images/country.jpg",
      title: "Country",
      text: "Stay in the loop with all the hottest new country music.",
    },
    {
      id: 13,
      link: "/music/playlist/1388965575/type/dz",
      image: "/images/metal.jpg",
      title: "Metal",
      text: "Explore the best metal tracks from the past and present.",
    }
  ];
  
  export const mood = [
    {
      id: 1,
      link: "/music/playlist/1479458365/type/dz",
      image: "/images/happy.jpg",
      title: "Happy",
      text: "Feel the joy with our happy playlist.",
    },
    {
      id: 2,
      link: "/music/playlist/1910358422/type/dz",
      image: "/images/sad.jpg",
      title: "Sad",
      text: "Embrace the emotions with our sad playlist.",
    },
    {
      id: 3,
      link: "/music/playlist/1976454162/type/dz",
      image: "/images/chill.jpg",
      title: "Chill",
      text: "Relax and unwind with our chill playlist.",
    },
    {
      id: 4,
      link: "/music/playlist/11081408402/type/dz",
      image: "/images/self-love.jpg",
      title: "Self-love",
      text: "Embrace yourself with our badass self-love playlist (IDGAF).",
    },
    {
      id: 5,
      link: "/music/playlist/4cJ8qUzt5CSTE9XN5uK2z2/type/sp",
      image: "/images/romantic.jpg",
      title: "Romantic",
      text: "Set the mood with our romantic playlist.",
    },
    {
      id: 6,
      link: "/music/playlist/2097558104/type/dz",
      image: "/images/party.jpg",
      title: "Party",
      text: "Get the party started with our upbeat playlist.",
    },
    {
      id: 7,
      link: "/music/playlist/2153050122/type/dz",
      image: "/images/workout.jpg",
      title: "Workout",
      text: "Stay motivated with our workout playlist.",
    },
    {
      id: 8,
      link: "/music/playlist/1306085715/type/dz",
      image: "/images/focus.jpg",
      title: "Focus",
      text: "Concentrate better with our focus playlist.",
    },
    {
      id: 9,
      link: "/music/playlist/733113466/type/dz",
      image: "/images/sleep.jpg",
      title: "Sleep",
      text: "Drift off to sleep with our calming playlist.",
    },
    {
      id: 10,
      link: "/music/playlist/10746894082/type/dz",
      image: "/images/gaming.jpg",
      title: "Gaming",
      text: "Get in the zone with our Phonk gaming playlist.",
    }
  ];
  
  export const animeVerse = [
    {
      id: 1,
      link: "/music/playlist/77fmI8qO4Y0ZXvVyeSr6VY/type/sp",
      image: "/images/aot.jpg",
      title: "Attack on Titan",
      text: "Experience the epic soundtrack of Attack on Titan.",
    },
    {
      id: 2,
      link: "/music/playlist/2Rskw6jbWzyTd4xbtlyJTO/type/sp",
      image: "/images/naruto.jpg",
      title: "Naruto",
      text: "Feel the nostalgia with Naruto's iconic soundtrack.",
    },
    {
      id: 3,
      link: "/music/playlist/4dbyVjvMaCfxY32ORFrKZx/type/sp",
      image: "/images/demon-slayer.jpg",
      title: "Demon Slayer",
      text: "Dive into the world of Demon Slayer with its stunning soundtrack.",
    },
    {
      id: 4,
      link: "/music/playlist/2SfdRdiYrcWXE0RulwgUpL/type/sp",
      image: "/images/frieren.jpg",
      title: "Frieren",
      text: "Immerse yourself in the world of Frieren with its beautiful soundtrack.",
    },
    {
      id: 5,
      link: "/music/playlist/7D0WJQIO0T1FnmqMQhGmyU/type/sp",
      image: "/images/tad.jpg",
      title: "The apothecary diaries",
      text: "Experience the enchanting world of The Apothecary Diaries with its captivating soundtrack.",
    },
    {
      id: 6,
      link: "/music/playlist/13071658123/type/dz",
      image: "/images/dandadan.jpg",
      title: "Dandadan",
      text: "Dive into the world of Dandadan with its captivating soundtrack.",
    },
    {
      id: 7,
      link: "/music/playlist/4CXUvJWg0ubdXC2MsaDM41/type/sp",
      image: "/images/spy-x-family.jpg",
      title: "Spy x Family",
      text: "Experience the blend of action and comedy with Spy x Family's soundtrack.",
    },
    {
      id: 8,
      link: "/music/playlist/12677797501/type/dz",
      image: "/images/kaiju.jpg",
      title: "Kaiju No. 8",
      text: "Immerse yourself in the world of Kaiju No. 8 with its thrilling soundtrack.",
    },
    {
      id: 9,
      link: "/music/playlist/0E6nx38s2K13qDL8YkbQ3F/type/sp",
      image: "/images/black-clover.jpg",
      title: "Black Clover",
      text: "Experience the magic of Black Clover's soundtrack.",
    },
    {
      id: 10,
      link: "/music/playlist/03d3KH6oFkoXk4syLWrk1s/type/sp",
      image: "/images/blue-lock.jpg",
      title: "Blue Lock",
      text: "Feel the adrenaline with Blue Lock's electrifying soundtrack.",
    },
    {
      id: 11,
      link: "/music/playlist/2HhaF1jOyLonX40otTfn4z/type/sp",
      image: "/images/one-piece.jpg",
      title: "One Piece",
      text: "Set sail with the adventurous soundtrack of One Piece.",
    },
    {
      id: 12,
      link: "/music/playlist/2bidxsC3QgXzEIKB6dnTIH/type/sp",
      image: "/images/bleach.jpg",
      title: "Bleach",
      text: "Experience the intense battles with Bleach's soundtrack.",
    },
    {
      id: 13,
      link: "/music/playlist/59QG71ZEdVV7xneRAWJo2b/type/sp",
      image: "/images/hxh.jpg",
      title: "Hunter x Hunter",
      text: "Explore the emotional depth of Hunter x Hunter's soundtrack.",
    },
    {
      id: 14,
      link: "/music/playlist/3OvtlM4CkLIhS9O6NadgQX/type/sp",
      image: "/images/jjk.jpg",
      title: "Jujutsu Kaisen",
      text: "Feel the thrill with Jujutsu Kaisen's electrifying soundtrack.",
    },
    {
      id: 15,
      link: "/music/playlist/28iePdgP3BmHzmGhjZlvrv/type/sp",
      image: "/images/solo.jpg",
      title: "Solo Leveling",
      text: "Experience the epic soundtrack of Solo Leveling.",
    },
    {
      id: 16,
      link: "/music/playlist/7270803764/type/dz",
      image: "/images/tokyo-ghoul.jpg",
      title: "Tokyo Ghoul",
      text: "Immerse yourself in the dark world of Tokyo Ghoul.",
    },
    {
      id: 17,
      link: "/music/playlist/58ti42AIci4jSmAVxwB094/type/sp",
      image: "/images/my-hero.jpg",
      title: "My Hero Academia",
      text: "Feel the heroism with My Hero Academia's soundtrack.",
    },
    {
      id: 18,
      link: "/music/playlist/3BIDgGeHvC0fuVFbF6cMas/type/sp",
      image: "/images/death-note.jpg",
      title: "Death Note",
      text: "Experience the psychological thriller of Death Note.",
    },
    {
      id: 19,
      link: "/music/playlist/5698032902/type/dz",
      image: "/images/sword-art.jpg",
      title: "Sword Art Online",
      text: "Dive into the virtual world of Sword Art Online.",
    },
    {
      id: 20,
      link: "/music/playlist/7iPIDAjUcqqgFGO24WUCua/type/sp",
      image: "/images/fairy-tail.jpg",
      title: "Fairy Tail",
      text: "Experience the magic of Fairy Tail's soundtrack.",
    },
    {
      id: 21,
      link: "/music/playlist/245VxdXB69INCDJfjuSLdJ/type/sp",
      image: "/images/fullmetal.jpg",
      title: "Fullmetal Alchemist",
      text: "Feel the depth of Fullmetal Alchemist's soundtrack.",
    },
    {
      id: 22,
      link: "/music/playlist/3eap0jJLCmA9biDsXnloeV/type/sp",
      image: "/images/dbz.jpg",
      title: "Dragon Ball Z",
      text: "Feel the power with Dragon Ball's iconic soundtrack.",
    },
    {
      id: 23,
      link: "/music/playlist/250TNmyz2qOzd00y0sglrW/type/sp",
      image: "/images/one-punch.jpg",
      title: "One Punch",
      text: "Experience the humor and action of One Punch",
    }
  ];

  export const kids = [
    {
      id: 1,
      link: "/music/playlist/3vHjFKeNa7SYCsuIEJRjjb/type/sp",
      image: "/images/disney.jpg",
      title: "Disney",
      text: "Explore the magical world of Disney with our curated playlist.",
    },
    {
      id: 2,
      link: "/music/playlist/1CKZs4Atk5gBaL40EUVZRg/type/sp",
      image: "/images/nursery.jpg",
      title: "Nursery Rhymes",
      text: "Enjoy the classic nursery rhymes that kids love.",
    },
    {
      id: 3,
      link: "/music/playlist/11958811001/type/dz",
      image: "/images/nick.jpg",
      title: "Nickelodeon sing along songs",
      text: "Sing along to your favorite Nickelodeon songs.",
  },
  {
      id: 6,
      link: "/music/playlist/6XMhvUe2OfARE6iEjhx96k/type/sp",
      image: "/images/lullabies.jpg",
      title: "Lullabies",
      text: "Relax and unwind with soothing lullabies for kids.",
    },
    {
      id: 4,
      link: "/music/playlist/12K4ZEoGgvnefBV0BZzu5N/type/sp",
      image: "/images/cn.jpg",
      title: "Cartoon Network",
      text: "Enjoy the catchy tunes from your favorite Cartoon Network shows.",
    },
    {
      id: 5,
      link: "/music/playlist/9415478102/type/dz",
      image: "/images/cocomelon.jpg",
      title: "Cocomelon",
      text: "Explore the fun and educational songs from Cocomelon.",
    },
    
    {
      id: 7,
      link: "/music/playlist/47kWkNwyIfBL20r7CMVuZS/type/sp",
      image: "/images/phonics.jpg",
      title: "Phonics",
      text: "Learn phonics with fun and engaging songs.",
    },
    {
      id: 8,
      link: "/music/playlist/47M7pLabZgxIPiVY6Bgmhi/type/sp",
      image: "/images/maths.jpg",
      title: "Maths Songs",
      text: "Explore the fun and educational songs about numbers.",
      },
    {
      id: 9,
      link: "/music/playlist/18CK2IfmSalVMFvOM9Ruu9/type/sp",
      image: "/images/science.jpg",
      title: "Science for kids",
      text: "Explore the fun and educational songs about science.",
    },
    
  ];